services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: catalog_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

# Instructions to run the MySQL container
# docker compose up -d
# docker exec -it mysql_local MySQL -u root -p